# https://starship.rs/config/

add_newline = true
format = """
[╭─ ](base)$sudo$username on $hostname at $directory$git_branch$package$nodejs$cmd_duration
[│](base)
[╰─ ](base)$character$line_break
"""
palette = "catppuccin_frappe"

[character]
success_symbol = "[❯](teal)"
error_symbol = "[x](red)"

[directory]
format = "[ $path](lavender)[$read_only]($read_only_style) "
read_only = " "
style = "bold #ffffff"
truncation_length = 2

[git_branch]
format = "| [$symbol$branch(:$remote_branch)](lavender) "


[hostname]
format = "[󰍹 $hostname](lavender)"
ssh_only = false
style = "bold #ffffff"

[nodejs]
format = "| [$symbol($version )](lavender)"

[package]
format = "| [$symbol $version](lavender) "
symbol = " "

[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"

[username]
style_user = "bold #000000"
style_root = "bold #000000"
format = "[ $user](lavender)"
disabled = false
show_always = true

